export const messaggi = [
 {
    id: 1,
    type: 'received',
    agentName: 'Mario Baroni',
    avatar: 'https://i.pravatar.cc/150?u=mario',
    subject: 'Appartamento via Massena confermato in pre-visita...',
    fullBody: 'Ciao, ti confermo che l\'appartamento di via Massena è stato bloccato per la pre-visita di domani alle 10:00.',
    time: '9:45',
    isRead: false, // Questo genera il "Da leggere: 1"
  },
  {
    id: 2,
    type: 'received',
    agentName: 'Franco Gallo',
    avatar: 'https://i.pravatar.cc/150?u=franco',
    subject: 'Nuovo set di creatività per le schede immobili caricato...',
    fullBody: 'Ho caricato le nuove foto sul drive condiviso. Fammi sapere se vanno bene per la pubblicazione.',
    time: '9:15',
    isRead: true,
  },
  {
    id: 3,
    type: 'received',
    agentName: 'Martina Lucario',
    avatar: 'https://i.pravatar.cc/150?u=martina',
    subject: 'Settimana chiusa sopra target. Manteniamo...',
    fullBody: 'Ottime notizie! Abbiamo superato il target settimanale del 15%.',
    time: 'Ieri',
    isRead: true,
  },
  {
    id: 4,
    type: 'sent',
    agentName: 'Mario Baroni',
    avatar: 'https://i.pravatar.cc/150?u=mario',
    subject: 'RE: Appartamento via Massena',
    fullBody: 'Perfetto Mario, procedi pure con la conferma al cliente.',
    time: '10:30',
    isRead: true,
  },
  {
    id: 5,
    type: 'sent',
    agentName: 'Martina Lucario',
    avatar: 'https://i.pravatar.cc/150?u=martina',
    subject: 'RE: Settimana chiusa sopra target',
    fullBody: 'Grandissimo lavoro Martina! Continuate così.',
    time: 'Ieri',
    isRead: true,
  },
];